# Generated by Django 3.2.3 on 2021-09-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='dateFound',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='dateResolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
