# Generated by Django 3.2.3 on 2021-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210904_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(blank=True, default='Unresolved', max_length=20, null=True),
        ),
    ]
