# Generated by Django 3.2.3 on 2021-09-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='duplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug', to='app.bug'),
        ),
    ]
